# Site settings
title: Mañana Records
email: hello@mananarecords.com
description: > #
    Un sello discografico profundamente latino
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mananarecords.com" # the base hostname & protocol for your site
paginate: 5

#Channels
youtube_channel: mananarecords
soundcloud_channel: mananarecords
facebook_channel:  mananarecords
twitter_channel:  mananarecords

# Build settings
markdown: kramdown
permalink: pretty

# collections:
#   blog:
#     output: true
#     sort_by: id