# Site settings
title: Mañana Records
email: hello@mananarecords.com
description: > #
    Mañana Records is a latin Net Label from Santiago de Chile.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mananarecords.com" # the base hostname & protocol for your site

#Channels
youtube_channel: mananarecords
soundcloud_channel: mananarecords
facebook_channel:  mananarecords


# Build settings
markdown: kramdown
permalink: pretty
