# Site settings
title: Mañana Records
email: contacto@manañarecords.com
description: > # 
  MAÑANA RECORDS IS CHACALEST MUSIC FOR THE DANCE AND FOR THE PEOPLE. 
  COME AND JOINS US LETS START THIS PARTY AND DANCE BORRACHOS NENA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mananarecords.com" # the base hostname & protocol for your site

#Channels
youtube_channel: mananarecords
soundcloud_channel: mananarecords
facebook_channel:  Mañana-Records-1687540664828672
twitter_channel: MananaRecords


# Build settings
markdown: kramdown
permalink: pretty
