# Site settings
title: Mañana Records
email: hello@mananarecords.com
description: > # 
    We are a novel Net Label from Santiago de Chile. Our catalog goes from tribal guarachero to krautrock with strokes of cumbia, chilean new wave, folk rock, and also pop. Only the chacalest music "for the dance and for the people".
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mananarecords.com" # the base hostname & protocol for your site

#Channels
youtube_channel: mananarecords
soundcloud_channel: mananarecords
facebook_channel:  mananarecords
twitter_channel: mananarecords


# Build settings
markdown: kramdown
permalink: pretty
